apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: reverse-proxy
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reverse-proxy
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50