apiVersion: v1
kind: Service
metadata:
  name: udagram-feed
  labels:
    service: udagram-feed
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: udagram-feed
  type: LoadBalancer