apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    service: reverse-proxy
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    service: reverse-proxy
  type: LoadBalancer