apiVersion: v1
kind: Service
metadata:
  name: udagram-user
  labels:
    service: udagram-user
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: udagram-user
  type: LoadBalancer