apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-feed
  name: udagram-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-feed
  template:
    metadata:
      labels:
        service: udagram-feed
    spec:
      containers:
      - image: impara8/project_udagram-api_feed
        name: udagram-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: setenv
              key: POSTGRES_USERNAME      
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret  